services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - pac
    volumes:
      - ./:/app
  mysql:
    image: "mysql"
    ports:
      - "${FORWARD_DATA_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "pac_database"
      MYSQL_USER: "pac"
      MYSQL_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "pac-mysql:/var/lib/mysql"
    networks:
      - pac
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "pac-redis:/data"
    networks:
      - pac
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - pac
  minio:
    image: "minio/minio:latest"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ROOT_USER: "pac"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - "pac-minio:/data/minio"
    networks:
      - pac
    command: minio server /data/minio --console-address ":8900"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s
networks:
  pac:
    name: papac-and-co-network
    driver: bridge
volumes:
  pac-mysql:
    driver: local
  pac-redis:
    driver: local
  pac-minio:
    driver: local
  pac-app:
    driver: local
